apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dot-5424
  janus-idp.io/tekton: dot-5424
  backstage.io/kubernetes-id: dot-5424
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dot-5424
resources: 
- deployment.yaml
- route.yaml
- service.yaml
