apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dot-5424
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dot-5424 
  name: dot-5424
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dot-5424
    weight: 100 
